const state={subject:null,trials:[],trial:null,review:null,preview:null,time:0,playing:false,raf:null,last:null,markStart:null,poll:null,editing:null,selectedUid:null,openRequest:0};
const $=id=>document.getElementById(id);
async function api(path,options){const r=await fetch(path,options);if(!r.ok){let msg=await r.text();try{const detail=JSON.parse(msg).detail;msg=Array.isArray(detail)?detail.map(x=>x.msg||String(x)).join('; '):detail}catch{}throw new Error(msg)}return r.json()}
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function clock(ns){const ms=Math.max(0,Math.floor(ns/1e6)),m=Math.floor(ms/60000),s=Math.floor(ms%60000/1000),x=ms%1000;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(x).padStart(3,'0')}`}
async function boot(){state.subject=await api('/api/subject');$('subject').textContent=`${state.subject.subject_id} · ${state.subject.reviewer_assignment}`;await loadTrials()}
function renderSummary(){const c=state.subject.counts||{},r=state.subject.reviews||{},queue=`${state.trials.length}/${c.total||0}`;$('summary').innerHTML=[['Queue',queue],['Pass',c.pass],['Warnings',c.warnings],['Reviewed',r.reviewed]].map(([k,v])=>`<div class="metric"><b>${v||0}</b><span>${k}</span></div>`).join('')}
async function loadTrials(){const q=new URLSearchParams({queue:$('queue').value});if($('task').value)q.set('task',$('task').value);state.trials=await api(`/api/trials?${q}`);const tasks=[...new Set(state.trials.map(x=>x.task_normalized))];const selected=$('task').value;$('task').innerHTML='<option value="">All tasks</option>'+tasks.map(x=>`<option ${x===selected?'selected':''}>${esc(x)}</option>`).join('');renderTrialList();renderSummary()}
function renderTrialList(){$('trials').innerHTML=state.trials.map(t=>`<button class="trial ${t.technical_qc_status==='PASS'?'pass':t.technical_qc_status==='FAIL'?'fail':'warn'} ${state.selectedUid===t.trial_uid?'active':''}" data-id="${esc(t.trial_uid)}"><b>${esc(t.task_normalized)} · ${esc(t.trial_directory_id)}</b><small>${esc(t.technical_qc_status)} · ${esc(t.review_status)}</small></button>`).join('');document.querySelectorAll('.trial').forEach(b=>b.onclick=()=>openTrial(b.dataset.id))}
function showWorkspaceMessage(message,loading=false){const empty=$('empty');empty.textContent=message;empty.classList.toggle('loading',loading);empty.hidden=false;$('review').hidden=true;$('workspace').scrollTop=0}
async function openTrial(uid){const request=++state.openRequest;pause();stopPolling();state.selectedUid=uid;renderTrialList();showWorkspaceMessage('Loading trial...',true);try{const [trial,review,preview]=await Promise.all([api(`/api/trials/${encodeURIComponent(uid)}`),api(`/api/trials/${encodeURIComponent(uid)}/review`),api(`/api/trials/${encodeURIComponent(uid)}/preview`)]);if(request!==state.openRequest)return;state.trial=trial;state.review=review;state.preview=preview;state.time=0;state.markStart=null;state.editing=null;$('empty').classList.remove('loading');$('empty').hidden=true;$('review').hidden=false;$('workspace').scrollTop=0;$('trial-title').textContent=uid;$('trial-meta').textContent=`${state.trial.technical_qc_status} · acquired ${state.trial.condition_acquired} · ${state.trial.duration_sec?.toFixed(2)||0}s`;const e=state.trial.effective_values||{};$('effective').textContent=`Effective: ${e.condition||'unknown'} · ${e.task_outcome||'unknown'} · ${e.primary_anomaly||'no anomaly label'}`;$('timeline').max=Math.max(1,Math.round((state.trial.duration_sec||0)*1e9));fillReview();renderPreview();renderAnnotations();loadTrials().catch(()=>{});if(state.preview.status==='missing')await prepare();else if(state.preview.status==='preparing')pollPreview(uid)}catch(e){if(request!==state.openRequest)return;showWorkspaceMessage(`Could not load trial: ${e.message}`)}}
function fillReview(){const f=$('review-form'),r=state.review;for(const name of ['review_status','condition_reviewed','task_outcome_reviewed','semantic_validity','primary_anomaly_reviewed','secondary_consequence_reviewed','manual_exclusion_reason','notes'])if(f.elements[name])f.elements[name].value=r[name]??'';for(const name of ['anomaly_present','usable_for_normal_training','usable_for_anomaly_evaluation'])f.elements[name].value=r[name]===null||r[name]===undefined?'':String(r[name])}
function nullableBool(value){return value===''?null:value==='true'}
function collectReview(){const f=$('review-form'),v=name=>f.elements[name].value||null;return {...state.review,review_status:v('review_status'),condition_reviewed:v('condition_reviewed'),task_outcome_reviewed:v('task_outcome_reviewed'),semantic_validity:v('semantic_validity'),primary_anomaly_reviewed:v('primary_anomaly_reviewed'),secondary_consequence_reviewed:v('secondary_consequence_reviewed'),manual_exclusion_reason:v('manual_exclusion_reason'),notes:f.elements.notes.value,anomaly_present:nullableBool(f.elements.anomaly_present.value),usable_for_normal_training:nullableBool(f.elements.usable_for_normal_training.value),usable_for_anomaly_evaluation:nullableBool(f.elements.usable_for_anomaly_evaluation.value),annotations:state.review.annotations}}
async function prepare(){if(!state.trial)return;const uid=state.trial.trial_uid;$('prepare').disabled=true;try{state.preview=await api(`/api/trials/${encodeURIComponent(uid)}/prepare`,{method:'POST'});renderPreview();if(state.preview.status==='preparing')pollPreview(uid)}catch(e){state.preview={status:'failed',error:e.message,retryable:true};renderPreview()}}
function pollPreview(uid){stopPolling();state.poll=setInterval(async()=>{if(state.trial?.trial_uid!==uid)return stopPolling();try{state.preview=await api(`/api/trials/${encodeURIComponent(uid)}/preview`);renderPreview();if(state.preview.status!=='preparing')stopPolling()}catch(e){state.preview={status:'failed',error:e.message,retryable:true};renderPreview();stopPolling()}},500)}
function stopPolling(){if(state.poll){clearInterval(state.poll);state.poll=null}}
function renderPreview(){const status=state.preview?.status||'missing',progress=Math.round((state.preview?.progress||0)*100);$('prepare').disabled=status==='preparing';$('prepare').textContent=status==='failed'?'Retry preview':status==='preparing'?`Preparing ${progress}%`:status==='ready'?'Preview ready':'Prepare preview';for(const key of ['camera1','camera2']){$(key).style.display='none';const missing=$('missing'+key.at(-1));missing.style.display='block';missing.textContent=status==='failed'?`Preview failed: ${state.preview.error}`:status==='preparing'?`Preparing preview ${progress}%`:'Unavailable'}renderPhases();renderAnnotationTrack();seek(state.time)}
function renderPhases(){const rows=state.preview?.phase_intervals||state.trial?.phase_intervals||[],duration=Math.max(1,Number($('timeline').max));$('phase-track').innerHTML=rows.map(p=>`<div class="phase" style="width:${Math.max(.2,(p.end_ns-p.start_ns)/duration*100)}%" title="${esc(p.phase)}">${esc(p.phase)}</div>`).join('')}
function seek(ns){state.time=Math.max(0,Math.min(Number($('timeline').max),Math.round(ns)));$('timeline').value=state.time;$('clock').value=clock(state.time);if(state.preview?.status!=='ready')return;for(const [key,imgId] of [['camera1_rgb','camera1'],['camera2_rgb','camera2']]){const stream=state.preview.streams[key],img=$(imgId),missing=$('missing'+imgId.at(-1));if(stream?.frames?.length){img.src=`/api/trials/${encodeURIComponent(state.trial.trial_uid)}/frame?topic_key=${key}&t_ns=${state.time}`;img.style.display='block';missing.style.display='none'}else{img.style.display='none';missing.style.display='block';missing.textContent='Camera stream missing'}}}
function toggle(){state.playing?pause():play()}
function play(){if(!state.trial||state.preview?.status!=='ready')return;state.playing=true;$('play').textContent='Pause';state.last=performance.now();const tick=now=>{if(!state.playing)return;state.time+=(now-state.last)*1e6*Number($('speed').value);state.last=now;if(state.time>=Number($('timeline').max)){seek(0);pause();return}seek(state.time);state.raf=requestAnimationFrame(tick)};state.raf=requestAnimationFrame(tick)}
function pause(){state.playing=false;$('play').textContent='Play';if(state.raf)cancelAnimationFrame(state.raf)}
function step(dir){const frames=state.preview?.streams?.camera1_rgb?.frames||[];if(!frames.length)return;const times=frames.map(x=>x.t_ns);let i=times.findIndex(x=>x>=state.time);if(i<0)i=times.length-1;i=Math.max(0,Math.min(times.length-1,i+dir));seek(times[i])}
function annotationDraft(start,end){const confidence=$('ann-confidence').value;return {annotation_id:state.editing===null?crypto.randomUUID():state.review.annotations[state.editing].annotation_id,annotation_type:$('ann-type').value,family:$('ann-family').value||null,subtype:$('ann-subtype').value||null,onset_ns:Math.round(start),offset_ns:Math.round(end),phase_at_onset:null,internal_phase_at_onset:null,primary:$('ann-primary').checked,severity:$('ann-severity').value||null,confidence:confidence===''?null:Number(confidence),reviewer_id:state.subject.reviewer_assignment,notes:$('ann-notes').value}}
function addPoint(){storeAnnotation(annotationDraft(state.time,state.time))}
function setStart(){state.markStart=state.time;$('save-status').textContent=`Interval starts at ${clock(state.time)}`}
function addInterval(){if(state.markStart===null){$('save-status').textContent='Set the interval start first';return}storeAnnotation(annotationDraft(Math.min(state.markStart,state.time),Math.max(state.markStart,state.time)));state.markStart=null}
function storeAnnotation(annotation){if(state.editing===null)state.review.annotations.push(annotation);else state.review.annotations[state.editing]=annotation;clearAnnotationEditor();renderAnnotations()}
function editAnnotation(index){const a=state.review.annotations[index];state.editing=index;$('ann-type').value=a.annotation_type;$('ann-family').value=a.family||'';$('ann-subtype').value=a.subtype||'';$('ann-severity').value=a.severity||'';$('ann-confidence').value=a.confidence??'';$('ann-primary').checked=!!a.primary;$('ann-notes').value=a.notes||'';$('cancel-edit').hidden=false;$('save-status').textContent=`Editing ${clock(a.onset_ns)}–${clock(a.offset_ns)}`}
function clearAnnotationEditor(){state.editing=null;state.markStart=null;for(const id of ['ann-family','ann-subtype','ann-severity','ann-confidence','ann-notes'])$(id).value='';$('ann-primary').checked=false;$('cancel-edit').hidden=true;$('save-status').textContent=''}
function renderAnnotations(){const rows=state.review?.annotations||[];$('annotations').innerHTML=rows.map((a,i)=>`<div class="ann-row" data-edit="${i}"><div><b>${esc(a.annotation_type)}${a.family?' · '+esc(a.family):''}</b><small>${clock(a.onset_ns)} – ${clock(a.offset_ns)}${a.primary?' · primary':''}</small></div><button data-delete="${i}" title="Delete annotation">×</button></div>`).join('');document.querySelectorAll('[data-edit]').forEach(row=>row.onclick=()=>editAnnotation(Number(row.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=e=>{e.stopPropagation();state.review.annotations.splice(Number(b.dataset.delete),1);clearAnnotationEditor();renderAnnotations()});renderAnnotationTrack()}
function renderAnnotationTrack(){if(!state.trial)return;const duration=Math.max(1,Number($('timeline').max));$('annotation-track').innerHTML=(state.review?.annotations||[]).map((a,i)=>{const left=a.onset_ns/duration*100,width=Math.max(.35,(a.offset_ns-a.onset_ns)/duration*100);return `<button class="ann-mark" data-track="${i}" style="left:${left}%;width:${width}%" title="${esc(a.annotation_type)}"></button>`}).join('');document.querySelectorAll('[data-track]').forEach(b=>b.onclick=()=>editAnnotation(Number(b.dataset.track)))}
async function save(next=false){const status=$('review-form').elements.review_status,previousStatus=status.value,autoComplete=next&&(status.value==='unreviewed'||status.value==='in_progress');if(autoComplete)status.value='reviewed';state.review=collectReview();const currentUid=state.trial.trial_uid,currentIndex=state.trials.findIndex(t=>t.trial_uid===currentUid),nextUid=currentIndex>=0?state.trials[currentIndex+1]?.trial_uid:null;$('save-status').textContent=next?'Completing review...':'Saving draft...';$('save').disabled=true;$('save-next').disabled=true;try{state.review=await api(`/api/trials/${encodeURIComponent(currentUid)}/review`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state.review)});state.subject=await api('/api/subject');await loadTrials();$('save-status').textContent=state.review.review_status==='reviewed'?'Review complete':'Saved';if(next){const currentRemains=state.trials.some(t=>t.trial_uid===currentUid),candidate=state.trials.some(t=>t.trial_uid===nextUid)?nextUid:!currentRemains?state.trials[0]?.trial_uid:null;if(candidate)await openTrial(candidate);else{pause();stopPolling();state.selectedUid=null;renderTrialList();showWorkspaceMessage(currentRemains?'End of queue.':'Queue complete.')}}}catch(e){if(autoComplete){status.value=previousStatus;state.review.review_status=previousStatus}$('save-status').textContent=e.message}finally{$('save').disabled=false;$('save-next').disabled=false}}
$('queue').onchange=loadTrials;$('task').onchange=loadTrials;$('prepare').onclick=prepare;$('play').onclick=toggle;$('timeline').oninput=e=>seek(Number(e.target.value));$('back').onclick=()=>step(-1);$('forward').onclick=()=>step(1);$('add-point').onclick=addPoint;$('mark-start').onclick=setStart;$('mark-end').onclick=addInterval;$('cancel-edit').onclick=clearAnnotationEditor;$('save').onclick=()=>save(false);$('save-next').onclick=()=>save(true);$('export').onclick=async()=>{const x=await api('/api/export',{method:'POST'});alert(`Exported ${x.trials} trials`)};boot().catch(e=>{$('empty').textContent=e.message});
